FROM mcr.microsoft.com/devcontainers/universal:2-linux

RUN apt-get update
RUN apt-get install -y curl
RUN pip install -r requirements.txt

 
 The  Dockerfile  is a standard Dockerfile that installs the Azure CLI. The  mcr.microsoft.com/devcontainers/universal:2-linux  image is a base image that includes the  Dockerfile  and  devcontainer.json  files. 
 The  devcontainer.json  file is a configuration